# Change these first
owner: Tech-Phantoms # Your GitHub organization or username, where this repository lives
repo: website-status # The name of this repository

sites:
  - name: Tech Phantoms website
    url: https://techphantoms.co
    
# NOTIFICATION_DISCORD: true
# NOTIFICATION_DISCORD_WEBHOOK: true
# NOTIFICATION_DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/907878980856741929/szU7PeQcr9rquoVC6uyT8bIhRj8BYfKVWw-Mgao-3mjmqnHTI5StjYqHwk6pWsL_PSOd

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://status.techphantoms.co
  # baseUrl: /website-status
  logoUrl: https://avatars.githubusercontent.com/u/61622105?s=100&v=4
  name: "Tech Phantoms status"
  theme: night
  introTitle: "**Tech Phantoms** open-source website monitoring."
  introMessage: "Powered by [Upptime](https://upptime.js.org/). Check our website: https://techphantoms.co"  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Tech-Phantoms/
    - title: Website
      href: https://techphantoms.co

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
