# Change these first
owner: Tech-Phantoms # Your GitHub organization or username, where this repository lives
repo: website-status # The name of this repository

NOTIFICATION_DISCORD: true
NOTIFICATION_DISCORD_WEBHOOK: true
NOTIFICATION_DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/907878980856741929/szU7PeQcr9rquoVC6uyT8bIhRj8BYfKVWw-Mgao-3mjmqnHTI5StjYqHwk6pWsL_PSOd

sites:
  - name: Tech Phantoms website
    url: https://techphantoms.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.techphantoms.co
  # baseUrl: /website-status
  logoUrl: https://raw.githubusercontent.com/Tech-Phantoms/community/main/assets/logo-750px.png
  name: "Status for Tech Phantoms' website"
  theme: night
  introTitle: "**Tech Phantoms** is an open-source community which focuses on tech-hiring, awareness, UX design, and so much more."
  introMessage: "Tech Phantoms is an open source community run by awesome students and early careers from our community. We hang out to share our knowledge and to build cool projects. We help each other with our doubts and also run community calls, resume reviews, and much more 🚀 Come hang out with us and let's make open source a better place 🔥 Join to our [Discord community](https://discord.apihacks.co) and follow us on [Twitter](https://twitter.com/tech_phantoms) to stay tuned about new announcements, projects, and much more 💥"  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Tech-Phantoms/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
